Add example using vite
redbadger/crux pull request #173
Opened 2024-01-08 11:15 UTC by nmrshll

closes #172

2024-01-10 09:35 UTC, StuartHarris commented
Thank you @nmrshll for contributing this. We'd be happy to merge it once a few things are sorted.
* it looks to me like this belongs to the `simple_counter` example rather than the `counter` example, so it should be moved
* The view model property to display the count should therefore be `.count` rather than `.text` — e.g. `<button>{view.getView().count}</button>` 
* I couldn't see where the shared library is being built (maybe I'm missing something). Maybe the `package.json` scripts should look something like this?
```json
  "scripts": {
    "dev": "pnpm run wasm:build && vite",
    "build": "pnpm run wasm:build && tsc && vite build",
    "preview": "vite preview",
    "wasm:build": "cd ../shared && wasm-pack build --target web"
  },
```

2024-01-10 09:37 UTC, StuartHarris requested changes

2024-01-10 09:37 UTC, StuartHarris commented on examples/counter/web-solid/index.html
> +<!doctype html>
I think all this belongs in `simple_counter`, rather than `counter`

2024-01-10 09:37 UTC, StuartHarris commented on examples/counter/web-solid/package.json
> +  "scripts": {
Do we need to build the `shared` lib?
```json
  "scripts": {
    "dev": "pnpm run wasm:build && vite",
    "build": "pnpm run wasm:build && tsc && vite build",
    "preview": "vite preview",
    "wasm:build": "cd ../shared && wasm-pack build --target web"
  }
```

2024-01-10 09:37 UTC, StuartHarris commented on examples/counter/web-solid/src/index.tsx
> +        <button>count is {view.getView().text}</button>
```tsx
<button>{view.getView().count}</button>
```

2024-01-10 09:49 UTC, StuartHarris commented
When I tested it, there was no styling. Any chance you could bring that in too? Thank you!

2024-02-19 08:56 UTC, StuartHarris commented
Hey @nmrshll this looks great now! Thank you for contributing. There's just a couple of minor things. The first is that we'll need a `.gitignore` file to exclude `node_modules`.

The second is that the `update()` function initialises the Wasm module every time it is called. It looks like this is idempotent, and so probably safe, but it does mean that there could be a slight delay (especially on poor bandwidth connections) when a button is first pressed, while the wasm is downloaded and initialised. I think a better approach would be to initialise the wasm module in `index.tsx`, instead. It looks like top-level await is supported so this should work...

```ts
import initCore from "shared";
await initCore();
```

Other than that would be happy to merge. Thank you.

2026-01-15 17:28 UTC, mhedgpeth commented
@nmrshll thanks for the PR! I'm doing some house keeping on the repo right now. Are you able to make the final changes requested so we can get this merged, or have you moved on and we should close this PR.

2026-01-24 00:04 UTC, mhedgpeth commented
@nmrshll it's looking like this PR is stale. Let me know if that's not the case and we can reopen to get things going.

2026-01-24 00:04 UTC, closed without merging